#!/usr/bin/env python

import sys, time, burger_server
from burger_daemon import BurgerDaemon

class BurgerRunner(BurgerDaemon):
    def run(self):
        burger_server.listen()

if __name__ == "__main__":
    runner = BurgerRunner('/tmp/burgerd.pid')

    if len(sys.argv) == 2:
        if sys.argv[1] == 'start':
            runner.start()
        elif sys.argv[1] == 'stop':
            runner.stop()
        elif sys.argv[1] == 'restart':
            runner.restart()
        else:
            print 'Invalid command.'
            sys.exit(2)

        sys.exit(0)
    else:
        print "usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)
